### ISSUE TITLE
[Bug] 为什么需要12000到12999这么多的端口，构建时许多的端口冲突，无法构建

### ISSUE THREAD

**Issue by guda0700** [nepsyn/minaplay#134]
### 现存的 issue 中存在您想提的问题吗

- [X] 我已查阅现存 issue，并且我目前的问题不在其中

### MinaPlay 版本

当前版本

### 问题定位

其他位置

### 问题描述

太多的端口冲突，怎么办？

### 系统日志

```text
提示有许多端口冲突
```

**Comment by nepsyn** [comment]
端口使用是为了提供实时语音服务，可以按需调整启动配置减少端口使用数量

```yaml
minaplay:
    environment:
        - MS_RTC_MAX_PORT=12100 # 语音服务的最大端口
    ports:
         - "12000-12100:12000-12100" # 调整端口映射数量
```
